language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=eagre_ecs/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: EWyWrwOLF34UZR56tSeDu5RdBWleZTNkhbek5QIFhXV1fPPIm8+McFQwz4Ylkg9s4t7KfPMLIu6uhXwCZZMinhTNmItoTGKZhwAVtZaXQc0ucqDjH4gwZKa+Ax2iH9gWALt7kqAbpkqxIaRfaSoppvGtusKGdadT57SkjE8ydvRIb0Qoovctj8ZRZloSiS1QlHcpRo/sa5X6gFBGkO97Zz99UFBVIvR3+WjgYPpNbJBGHDV2MUYus/57ldUYPa8MsQM4m+7x4MzNYVkIuENQJtJSVgFu6+eAxvllodfZdNOqYxXQCFLFXKbVIZyKbr2k2X9Wg8/+01nMBlPzMDpsCIDPNQslV8t1zMD19bhAMlUJllbnMM9B6wyjGgtatC8h0sPgQk3OcJjpFgwOcWE1IMohsmozns/ggC711WOWO3OTKYoOUmH6YeWHvf4eIre3BNx+EY5mN7nTOQe9RD1y4EqSSKg3GvKlCueaaQsAIeCzpEeZFdFp0v8oihVcDlPmHYOKGFmuqKsLIxAlQXON8p+OdXTuQuzEIlGYFQkT7nPinOgizT/Uvaj0GVcxw8pwvCdq12Wd4Erc2tAs4klNpzJz/D24lup25UqW7EU9cctq/lJEnyOjTTV+qU7XkWl0XVHphVy0pY9mDQzRdkj5GXSXNC1vw6u8ZebBdo7JX4Y=
